// Generated by CoffeeScript 1.6.3
window.webcam = function(id, cb) {
  var captureImage, connect, el, error;
  if (id == null) {
    id = "canvasHolder";
  }
  if (cb == null) {
    cb = function() {};
  }
  connect = function(stream) {
    var video;
    video = document.getElementById("video");
    video.src = (window.URL ? window.URL.createObjectURL(stream) : stream);
    return video.play();
  };
  error = function(e) {
    return console.log(e);
  };
  captureImage = function() {
    var canvas, ctx, dataURL, video;
    video = document.getElementById("video");
    canvas = document.createElement("canvas");
    canvas.id = "hiddenCanvas";
    document.body.appendChild(canvas);
    document.getElementById(id).appendChild(canvas);
    ctx = canvas.getContext("2d");
    ctx.drawImage(video, 0, 0, 700, 300);
    dataURL = canvas.toDataURL();
    console.log(dataURL);
    return cb(dataURL);
  };
  navigator.myGetMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;
  navigator.myGetMedia({
    video: true
  }, connect, error);
  el = document.getElementById("video");
  return el.addEventListener("click", captureImage, false);
};

/*
//@ sourceMappingURL=webcam.map
*/
